# Generated by Django 5.1.6 on 2026-03-12 23:13

import django.core.validators
import relacionamentos.validators.validator_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(help_text='Insira um CPF válido', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validator_cpf.valida_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Nome da pessoa', max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
