# Generated by Django 5.1.6 on 2026-03-12 23:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0004_alter_passaporte_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passaporte',
            name='emissao',
            field=models.DateField(help_text='Selecione a data de emissão do passaporte', validators=[django.core.validators.MinValueValidator(datetime.date.today), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Emissão'),
        ),
    ]
