# Generated by Django 5.1.6 on 2026-03-13 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0005_alter_passaporte_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='Insira o e-mail institucional', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
    ]
