# Generated by Django 5.1.6 on 2026-03-13 00:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0006_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do artigo', max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('publicacao', models.DateField(help_text='Selecione a data de publicação do artigo', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('autor', models.ForeignKey(help_text='Selecione o reporter autor do artigo', on_delete=django.db.models.deletion.CASCADE, to='relacionamentos.reporter', verbose_name='Reporter autor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
