# Generated by Django 5.1.6 on 2026-03-13 01:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0008_revista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='TInsira o título da reportagem', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('publicacao', models.DateField(help_text='Selecione a data de publicação da reportagem', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Publicação')),
                ('revistas', models.ManyToManyField(help_text='Selecione as revistas nas quais a reportagem foi publicada', to='relacionamentos.revista')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
