# Generated by Django 5.1.6 on 2026-03-19 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0009_reportagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relacionamentos.pessoa')),
                ('email', models.EmailField(help_text='E-mail institucional do aluno', max_length=254, verbose_name='E-mail')),
                ('cod', models.CharField(help_text='Digite a matrícula do aluno', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
            bases=('relacionamentos.pessoa',),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da disciplina', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sigla', models.CharField(help_text='Sigla da disciplina', max_length=5, validators=[django.core.validators.MinLengthValidator(3)])),
                ('semestre', models.IntegerField(help_text='Semestre da disciplina', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ementa', models.TextField(help_text='Ementa da disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='reportagem',
            options={'verbose_name_plural': 'Reportagens'},
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Insira a data da matricula')),
                ('nota', models.FloatField(help_text='Nota final do aluno', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10, 0)])),
                ('frequencia', models.FloatField(help_text='Informa a frequencia final do aluno', verbose_name='Frequência')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Aprovado em exame', 'Aprovado em exame'), ('Em Exame', 'Em Exame'), ('Matriculado', 'Matriculado'), ('Reprovado', 'Reprovado'), ('Trancado', 'Trancado')], default='Matriculado', help_text='Status do aluno para a matricula', max_length=20)),
                ('aluno', models.ForeignKey(help_text='Selecione o aluno para a matricula', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.aluno')),
                ('disciplina', models.ForeignKey(help_text='Selecione o disciplina para o aluno', on_delete=django.db.models.deletion.PROTECT, to='relacionamentos.disciplina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(help_text='Selecione as disciplinas do aluno', through='relacionamentos.Matricula', to='relacionamentos.disciplina'),
        ),
    ]
