# Generated by Django 5.1.6 on 2026-03-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0004_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='area',
            field=models.CharField(blank=True, help_text='Informe a área do conhecimento segundo o padrão CAPES.', max_length=20, null=True, verbose_name='Área do conhecimento'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='instituicao',
            field=models.CharField(default='IFRS', help_text='Digite a instituição com no máximo 10 caracteres.', max_length=10, verbose_name='Instituição'),
        ),
    ]
