# Generated by Django 5.1.6 on 2026-03-03 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0005_alter_categoria_area_alter_categoria_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
