# Generated by Django 5.1.6 on 2026-03-09 22:38

import django.core.validators
import exemplo.validators.memory_validator
import exemplo.validators.palavras_proibidas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0006_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(help_text='Codigo do problema', unique=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('titulo', models.CharField(help_text='Titulo do problema', max_length=100, validators=[django.core.validators.MinValueValidator(3), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='O campo contém palavras que foram proibidas. Ex: teste, admin')], verbose_name='Titulo')),
                ('nivel', models.IntegerField(choices=[(1, 'Um'), (2, 'Dois'), (3, 'Três'), (4, 'Quatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Sete'), (8, 'Oito'), (9, 'Nove')], default=1, help_text='Escolha o nivel do problema', verbose_name='Nivel')),
                ('descricao', models.TextField(help_text='Insira a descrição do problema para o usuário', max_length=2000, validators=[django.core.validators.MinLengthValidator(20), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['irã', 'trump', 'eua'], mensagem='O campo contém palavras que foram proibidas. Revise as diretrizes')], verbose_name='Descrição')),
                ('exemplo_entrada', models.TextField(help_text='Entrada para a solução do problema', max_length=2000, verbose_name='Exemplo de entrada')),
                ('exemplo_saida', models.TextField(help_text='Saida esperada para a solução do problema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Exemplo de saida')),
                ('testes_entrada', models.TextField(help_text='Entrada para a solução do problema', max_length=2000, verbose_name='Exemplo de entrada')),
                ('testes_saida', models.TextField(help_text='Saida esperada para a solução do problema', max_length=2000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Exemplo de saida')),
                ('pontuacao', models.FloatField(help_text='Insira a pontuação a ser creditada para o usuario', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Pontuação')),
                ('tempo_execucao', models.IntegerField(help_text='Insira o tempo maximo de execução do programa', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Tempo de execucao do programa')),
                ('memoria_maxima', models.IntegerField(help_text='Informe a quantidade maxima em MB de memoria maxima a ser utilizada', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(256), exemplo.validators.memory_validator.validar_tamanho_memoria], verbose_name='Memoria maxima')),
                ('resolvidos', models.IntegerField(default=0, help_text='Quantidade de usuarios que resolveram o problema', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resolvidos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
