# Generated by Django 5.1.6 on 2026-03-09 23:02

import django.core.validators
import exemplo.validators.palavras_proibidas
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0007_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='titulo',
            field=models.CharField(help_text='Titulo do problema', max_length=100, validators=[django.core.validators.MinLengthValidator(3), exemplo.validators.palavras_proibidas.PalavrasProibidas(lista_proibida=['teste', 'admin'], mensagem='O campo contém palavras que foram proibidas. Ex: teste, admin')], verbose_name='Titulo'),
        ),
    ]
