# Generated by Django 5.1.6 on 2026-03-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0008_alter_problema_titulo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problema',
            unique_together={('titulo', 'nivel')},
        ),
    ]
