# Generated by Django 5.1.6 on 2026-03-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0009_alter_problema_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problema',
            options={'ordering': ['titulo'], 'verbose_name': 'Problema de Computação', 'verbose_name_plural': 'Problemas de Computação'},
        ),
    ]
