# Generated by Django 5.1.6 on 2026-03-29 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0010_alter_problema_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('estado', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sobrenome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nome_usuario', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pais', models.TextField(choices=[('BR', 'BRASIL'), ('EUA', 'Estados Unidos'), ('IRA', 'Irã'), ('ARG', 'Argentina'), ('OUT', 'Outro')], default='OUT')),
                ('email', models.EmailField(max_length=254)),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('profissao', models.TextField(choices=[('Estudante', 'Estudante'), ('Programador', 'Programador'), ('Desempregado', 'Desempregado'), ('Professor', 'Professor'), ('Analista', 'Analista de Sistemas')], default='Estudante')),
                ('sobre', models.TextField()),
                ('instituicao', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('responsavel', models.CharField(max_length=100)),
                ('idade', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(200)])),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sexo', models.TextField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')])),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exemplo.cidade')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exemplo.esporte')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exemplo.time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
